// Code generated by MockGen. DO NOT EDIT.
// Source: agentcore.go
//
// Generated by this command:
//
//	mockgen -source=agentcore.go -destination=agentcore_mock.go -package=client -write_package_comment=false
package client

import (
	context "context"
	reflect "reflect"

	bedrockagentcorecontrol "github.com/aws/aws-sdk-go-v2/service/bedrockagentcorecontrol"
	gomock "go.uber.org/mock/gomock"
)

// MockIAgentCore is a mock of IAgentCore interface.
type MockIAgentCore struct {
	ctrl     *gomock.Controller
	recorder *MockIAgentCoreMockRecorder
}

// MockIAgentCoreMockRecorder is the mock recorder for MockIAgentCore.
type MockIAgentCoreMockRecorder struct {
	mock *MockIAgentCore
}

// NewMockIAgentCore creates a new mock instance.
func NewMockIAgentCore(ctrl *gomock.Controller) *MockIAgentCore {
	mock := &MockIAgentCore{ctrl: ctrl}
	mock.recorder = &MockIAgentCoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAgentCore) EXPECT() *MockIAgentCoreMockRecorder {
	return m.recorder
}

// GetAgentRuntime mocks base method.
func (m *MockIAgentCore) GetAgentRuntime(ctx context.Context, runtimeId *string) (*bedrockagentcorecontrol.GetAgentRuntimeOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentRuntime", ctx, runtimeId)
	ret0, _ := ret[0].(*bedrockagentcorecontrol.GetAgentRuntimeOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgentRuntime indicates an expected call of GetAgentRuntime.
func (mr *MockIAgentCoreMockRecorder) GetAgentRuntime(ctx, runtimeId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentRuntime", reflect.TypeOf((*MockIAgentCore)(nil).GetAgentRuntime), ctx, runtimeId)
}

// UpdateAgentRuntime mocks base method.
func (m *MockIAgentCore) UpdateAgentRuntime(ctx context.Context, input *bedrockagentcorecontrol.UpdateAgentRuntimeInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAgentRuntime", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAgentRuntime indicates an expected call of UpdateAgentRuntime.
func (mr *MockIAgentCoreMockRecorder) UpdateAgentRuntime(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAgentRuntime", reflect.TypeOf((*MockIAgentCore)(nil).UpdateAgentRuntime), ctx, input)
}
