// Code generated by MockGen. DO NOT EDIT.
// Source: athena.go
//
// Generated by this command:
//
//	mockgen -source=athena.go -destination=athena_mock.go -package=client -write_package_comment=false
package client

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIAthena is a mock of IAthena interface.
type MockIAthena struct {
	ctrl     *gomock.Controller
	recorder *MockIAthenaMockRecorder
}

// MockIAthenaMockRecorder is the mock recorder for MockIAthena.
type MockIAthenaMockRecorder struct {
	mock *MockIAthena
}

// NewMockIAthena creates a new mock instance.
func NewMockIAthena(ctrl *gomock.Controller) *MockIAthena {
	mock := &MockIAthena{ctrl: ctrl}
	mock.recorder = &MockIAthenaMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAthena) EXPECT() *MockIAthenaMockRecorder {
	return m.recorder
}

// CheckAthenaWorkGroupExists mocks base method.
func (m *MockIAthena) CheckAthenaWorkGroupExists(ctx context.Context, workGroupName *string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAthenaWorkGroupExists", ctx, workGroupName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAthenaWorkGroupExists indicates an expected call of CheckAthenaWorkGroupExists.
func (mr *MockIAthenaMockRecorder) CheckAthenaWorkGroupExists(ctx, workGroupName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAthenaWorkGroupExists", reflect.TypeOf((*MockIAthena)(nil).CheckAthenaWorkGroupExists), ctx, workGroupName)
}

// DeleteWorkGroup mocks base method.
func (m *MockIAthena) DeleteWorkGroup(ctx context.Context, workGroupName *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWorkGroup", ctx, workGroupName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWorkGroup indicates an expected call of DeleteWorkGroup.
func (mr *MockIAthenaMockRecorder) DeleteWorkGroup(ctx, workGroupName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkGroup", reflect.TypeOf((*MockIAthena)(nil).DeleteWorkGroup), ctx, workGroupName)
}
