// Code generated by MockGen. DO NOT EDIT.
// Source: cloudformation.go
//
// Generated by this command:
//
//	mockgen -source=cloudformation.go -destination=cloudformation_mock.go -package=client -write_package_comment=false
package client

import (
	context "context"
	reflect "reflect"

	types "github.com/aws/aws-sdk-go-v2/service/cloudformation/types"
	gomock "go.uber.org/mock/gomock"
)

// MockICloudFormation is a mock of ICloudFormation interface.
type MockICloudFormation struct {
	ctrl     *gomock.Controller
	recorder *MockICloudFormationMockRecorder
}

// MockICloudFormationMockRecorder is the mock recorder for MockICloudFormation.
type MockICloudFormationMockRecorder struct {
	mock *MockICloudFormation
}

// NewMockICloudFormation creates a new mock instance.
func NewMockICloudFormation(ctrl *gomock.Controller) *MockICloudFormation {
	mock := &MockICloudFormation{ctrl: ctrl}
	mock.recorder = &MockICloudFormationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICloudFormation) EXPECT() *MockICloudFormationMockRecorder {
	return m.recorder
}

// DeleteStack mocks base method.
func (m *MockICloudFormation) DeleteStack(ctx context.Context, stackName *string, retainResources []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStack", ctx, stackName, retainResources)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStack indicates an expected call of DeleteStack.
func (mr *MockICloudFormationMockRecorder) DeleteStack(ctx, stackName, retainResources any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStack", reflect.TypeOf((*MockICloudFormation)(nil).DeleteStack), ctx, stackName, retainResources)
}

// DescribeStacks mocks base method.
func (m *MockICloudFormation) DescribeStacks(ctx context.Context, stackName *string) ([]types.Stack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeStacks", ctx, stackName)
	ret0, _ := ret[0].([]types.Stack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeStacks indicates an expected call of DescribeStacks.
func (mr *MockICloudFormationMockRecorder) DescribeStacks(ctx, stackName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeStacks", reflect.TypeOf((*MockICloudFormation)(nil).DescribeStacks), ctx, stackName)
}

// GetTemplate mocks base method.
func (m *MockICloudFormation) GetTemplate(ctx context.Context, stackName *string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplate", ctx, stackName)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplate indicates an expected call of GetTemplate.
func (mr *MockICloudFormationMockRecorder) GetTemplate(ctx, stackName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplate", reflect.TypeOf((*MockICloudFormation)(nil).GetTemplate), ctx, stackName)
}

// ListStackResources mocks base method.
func (m *MockICloudFormation) ListStackResources(ctx context.Context, stackName *string) ([]types.StackResourceSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStackResources", ctx, stackName)
	ret0, _ := ret[0].([]types.StackResourceSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStackResources indicates an expected call of ListStackResources.
func (mr *MockICloudFormationMockRecorder) ListStackResources(ctx, stackName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStackResources", reflect.TypeOf((*MockICloudFormation)(nil).ListStackResources), ctx, stackName)
}

// UpdateStack mocks base method.
func (m *MockICloudFormation) UpdateStack(ctx context.Context, stackName, templateBody *string, parameters []types.Parameter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStack", ctx, stackName, templateBody, parameters)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStack indicates an expected call of UpdateStack.
func (mr *MockICloudFormationMockRecorder) UpdateStack(ctx, stackName, templateBody, parameters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStack", reflect.TypeOf((*MockICloudFormation)(nil).UpdateStack), ctx, stackName, templateBody, parameters)
}

// UpdateStackWithTemplateURL mocks base method.
func (m *MockICloudFormation) UpdateStackWithTemplateURL(ctx context.Context, stackName, templateURL *string, parameters []types.Parameter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStackWithTemplateURL", ctx, stackName, templateURL, parameters)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStackWithTemplateURL indicates an expected call of UpdateStackWithTemplateURL.
func (mr *MockICloudFormationMockRecorder) UpdateStackWithTemplateURL(ctx, stackName, templateURL, parameters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStackWithTemplateURL", reflect.TypeOf((*MockICloudFormation)(nil).UpdateStackWithTemplateURL), ctx, stackName, templateURL, parameters)
}
