// Code generated by MockGen. DO NOT EDIT.
// Source: cloudwatchlogs.go
//
// Generated by this command:
//
//	mockgen -source=cloudwatchlogs.go -destination=cloudwatchlogs_mock.go -package=client -write_package_comment=false
//

package client

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockICloudWatchLogs is a mock of ICloudWatchLogs interface.
type MockICloudWatchLogs struct {
	ctrl     *gomock.Controller
	recorder *MockICloudWatchLogsMockRecorder
	isgomock struct{}
}

// MockICloudWatchLogsMockRecorder is the mock recorder for MockICloudWatchLogs.
type MockICloudWatchLogsMockRecorder struct {
	mock *MockICloudWatchLogs
}

// NewMockICloudWatchLogs creates a new mock instance.
func NewMockICloudWatchLogs(ctrl *gomock.Controller) *MockICloudWatchLogs {
	mock := &MockICloudWatchLogs{ctrl: ctrl}
	mock.recorder = &MockICloudWatchLogsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICloudWatchLogs) EXPECT() *MockICloudWatchLogsMockRecorder {
	return m.recorder
}

// CheckLogGroupDeletionProtection mocks base method.
func (m *MockICloudWatchLogs) CheckLogGroupDeletionProtection(ctx context.Context, logGroupName *string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckLogGroupDeletionProtection", ctx, logGroupName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckLogGroupDeletionProtection indicates an expected call of CheckLogGroupDeletionProtection.
func (mr *MockICloudWatchLogsMockRecorder) CheckLogGroupDeletionProtection(ctx, logGroupName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckLogGroupDeletionProtection", reflect.TypeOf((*MockICloudWatchLogs)(nil).CheckLogGroupDeletionProtection), ctx, logGroupName)
}

// DisableLogGroupDeletionProtection mocks base method.
func (m *MockICloudWatchLogs) DisableLogGroupDeletionProtection(ctx context.Context, logGroupName *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableLogGroupDeletionProtection", ctx, logGroupName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableLogGroupDeletionProtection indicates an expected call of DisableLogGroupDeletionProtection.
func (mr *MockICloudWatchLogsMockRecorder) DisableLogGroupDeletionProtection(ctx, logGroupName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableLogGroupDeletionProtection", reflect.TypeOf((*MockICloudWatchLogs)(nil).DisableLogGroupDeletionProtection), ctx, logGroupName)
}
