// Code generated by MockGen. DO NOT EDIT.
// Source: cognito.go
//
// Generated by this command:
//
//	mockgen -source=cognito.go -destination=cognito_mock.go -package=client -write_package_comment=false
//

package client

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockICognito is a mock of ICognito interface.
type MockICognito struct {
	ctrl     *gomock.Controller
	recorder *MockICognitoMockRecorder
	isgomock struct{}
}

// MockICognitoMockRecorder is the mock recorder for MockICognito.
type MockICognitoMockRecorder struct {
	mock *MockICognito
}

// NewMockICognito creates a new mock instance.
func NewMockICognito(ctrl *gomock.Controller) *MockICognito {
	mock := &MockICognito{ctrl: ctrl}
	mock.recorder = &MockICognitoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICognito) EXPECT() *MockICognitoMockRecorder {
	return m.recorder
}

// CheckUserPoolDeletionProtection mocks base method.
func (m *MockICognito) CheckUserPoolDeletionProtection(ctx context.Context, userPoolId *string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserPoolDeletionProtection", ctx, userPoolId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserPoolDeletionProtection indicates an expected call of CheckUserPoolDeletionProtection.
func (mr *MockICognitoMockRecorder) CheckUserPoolDeletionProtection(ctx, userPoolId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserPoolDeletionProtection", reflect.TypeOf((*MockICognito)(nil).CheckUserPoolDeletionProtection), ctx, userPoolId)
}

// DisableUserPoolDeletionProtection mocks base method.
func (m *MockICognito) DisableUserPoolDeletionProtection(ctx context.Context, userPoolId *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableUserPoolDeletionProtection", ctx, userPoolId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableUserPoolDeletionProtection indicates an expected call of DisableUserPoolDeletionProtection.
func (mr *MockICognitoMockRecorder) DisableUserPoolDeletionProtection(ctx, userPoolId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableUserPoolDeletionProtection", reflect.TypeOf((*MockICognito)(nil).DisableUserPoolDeletionProtection), ctx, userPoolId)
}
