// Code generated by MockGen. DO NOT EDIT.
// Source: ec2.go
//
// Generated by this command:
//
//	mockgen -source=ec2.go -destination=ec2_mock.go -package=client -write_package_comment=false
//

package client

import (
	context "context"
	reflect "reflect"

	types "github.com/aws/aws-sdk-go-v2/service/ec2/types"
	gomock "go.uber.org/mock/gomock"
)

// MockIEC2 is a mock of IEC2 interface.
type MockIEC2 struct {
	ctrl     *gomock.Controller
	recorder *MockIEC2MockRecorder
	isgomock struct{}
}

// MockIEC2MockRecorder is the mock recorder for MockIEC2.
type MockIEC2MockRecorder struct {
	mock *MockIEC2
}

// NewMockIEC2 creates a new mock instance.
func NewMockIEC2(ctrl *gomock.Controller) *MockIEC2 {
	mock := &MockIEC2{ctrl: ctrl}
	mock.recorder = &MockIEC2MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIEC2) EXPECT() *MockIEC2MockRecorder {
	return m.recorder
}

// CheckTerminationProtection mocks base method.
func (m *MockIEC2) CheckTerminationProtection(ctx context.Context, instanceId *string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckTerminationProtection", ctx, instanceId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckTerminationProtection indicates an expected call of CheckTerminationProtection.
func (mr *MockIEC2MockRecorder) CheckTerminationProtection(ctx, instanceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckTerminationProtection", reflect.TypeOf((*MockIEC2)(nil).CheckTerminationProtection), ctx, instanceId)
}

// DeleteNetworkInterface mocks base method.
func (m *MockIEC2) DeleteNetworkInterface(ctx context.Context, networkInterfaceId *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNetworkInterface", ctx, networkInterfaceId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNetworkInterface indicates an expected call of DeleteNetworkInterface.
func (mr *MockIEC2MockRecorder) DeleteNetworkInterface(ctx, networkInterfaceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNetworkInterface", reflect.TypeOf((*MockIEC2)(nil).DeleteNetworkInterface), ctx, networkInterfaceId)
}

// DeleteSecurityGroup mocks base method.
func (m *MockIEC2) DeleteSecurityGroup(ctx context.Context, securityGroupId *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSecurityGroup", ctx, securityGroupId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSecurityGroup indicates an expected call of DeleteSecurityGroup.
func (mr *MockIEC2MockRecorder) DeleteSecurityGroup(ctx, securityGroupId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSecurityGroup", reflect.TypeOf((*MockIEC2)(nil).DeleteSecurityGroup), ctx, securityGroupId)
}

// DeleteSubnet mocks base method.
func (m *MockIEC2) DeleteSubnet(ctx context.Context, subnetId *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubnet", ctx, subnetId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubnet indicates an expected call of DeleteSubnet.
func (mr *MockIEC2MockRecorder) DeleteSubnet(ctx, subnetId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubnet", reflect.TypeOf((*MockIEC2)(nil).DeleteSubnet), ctx, subnetId)
}

// DeleteVpcEndpointServiceConfiguration mocks base method.
func (m *MockIEC2) DeleteVpcEndpointServiceConfiguration(ctx context.Context, serviceId *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVpcEndpointServiceConfiguration", ctx, serviceId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVpcEndpointServiceConfiguration indicates an expected call of DeleteVpcEndpointServiceConfiguration.
func (mr *MockIEC2MockRecorder) DeleteVpcEndpointServiceConfiguration(ctx, serviceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVpcEndpointServiceConfiguration", reflect.TypeOf((*MockIEC2)(nil).DeleteVpcEndpointServiceConfiguration), ctx, serviceId)
}

// DescribeNetworkInterfaces mocks base method.
func (m *MockIEC2) DescribeNetworkInterfaces(ctx context.Context, filters []types.Filter) ([]types.NetworkInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeNetworkInterfaces", ctx, filters)
	ret0, _ := ret[0].([]types.NetworkInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeNetworkInterfaces indicates an expected call of DescribeNetworkInterfaces.
func (mr *MockIEC2MockRecorder) DescribeNetworkInterfaces(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeNetworkInterfaces", reflect.TypeOf((*MockIEC2)(nil).DescribeNetworkInterfaces), ctx, filters)
}

// DescribeVpcEndpointConnections mocks base method.
func (m *MockIEC2) DescribeVpcEndpointConnections(ctx context.Context, serviceId *string) ([]types.VpcEndpointConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeVpcEndpointConnections", ctx, serviceId)
	ret0, _ := ret[0].([]types.VpcEndpointConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeVpcEndpointConnections indicates an expected call of DescribeVpcEndpointConnections.
func (mr *MockIEC2MockRecorder) DescribeVpcEndpointConnections(ctx, serviceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeVpcEndpointConnections", reflect.TypeOf((*MockIEC2)(nil).DescribeVpcEndpointConnections), ctx, serviceId)
}

// DisableTerminationProtection mocks base method.
func (m *MockIEC2) DisableTerminationProtection(ctx context.Context, instanceId *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableTerminationProtection", ctx, instanceId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableTerminationProtection indicates an expected call of DisableTerminationProtection.
func (mr *MockIEC2MockRecorder) DisableTerminationProtection(ctx, instanceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableTerminationProtection", reflect.TypeOf((*MockIEC2)(nil).DisableTerminationProtection), ctx, instanceId)
}

// RejectVpcEndpointConnections mocks base method.
func (m *MockIEC2) RejectVpcEndpointConnections(ctx context.Context, serviceId *string, vpcEndpointIds []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectVpcEndpointConnections", ctx, serviceId, vpcEndpointIds)
	ret0, _ := ret[0].(error)
	return ret0
}

// RejectVpcEndpointConnections indicates an expected call of RejectVpcEndpointConnections.
func (mr *MockIEC2MockRecorder) RejectVpcEndpointConnections(ctx, serviceId, vpcEndpointIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectVpcEndpointConnections", reflect.TypeOf((*MockIEC2)(nil).RejectVpcEndpointConnections), ctx, serviceId, vpcEndpointIds)
}
