// Code generated by MockGen. DO NOT EDIT.
// Source: elbv2.go
//
// Generated by this command:
//
//	mockgen -source=elbv2.go -destination=elbv2_mock.go -package=client -write_package_comment=false
//

package client

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIELBV2 is a mock of IELBV2 interface.
type MockIELBV2 struct {
	ctrl     *gomock.Controller
	recorder *MockIELBV2MockRecorder
	isgomock struct{}
}

// MockIELBV2MockRecorder is the mock recorder for MockIELBV2.
type MockIELBV2MockRecorder struct {
	mock *MockIELBV2
}

// NewMockIELBV2 creates a new mock instance.
func NewMockIELBV2(ctrl *gomock.Controller) *MockIELBV2 {
	mock := &MockIELBV2{ctrl: ctrl}
	mock.recorder = &MockIELBV2MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIELBV2) EXPECT() *MockIELBV2MockRecorder {
	return m.recorder
}

// CheckLoadBalancerDeletionProtection mocks base method.
func (m *MockIELBV2) CheckLoadBalancerDeletionProtection(ctx context.Context, loadBalancerArn *string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckLoadBalancerDeletionProtection", ctx, loadBalancerArn)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckLoadBalancerDeletionProtection indicates an expected call of CheckLoadBalancerDeletionProtection.
func (mr *MockIELBV2MockRecorder) CheckLoadBalancerDeletionProtection(ctx, loadBalancerArn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckLoadBalancerDeletionProtection", reflect.TypeOf((*MockIELBV2)(nil).CheckLoadBalancerDeletionProtection), ctx, loadBalancerArn)
}

// DisableLoadBalancerDeletionProtection mocks base method.
func (m *MockIELBV2) DisableLoadBalancerDeletionProtection(ctx context.Context, loadBalancerArn *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableLoadBalancerDeletionProtection", ctx, loadBalancerArn)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableLoadBalancerDeletionProtection indicates an expected call of DisableLoadBalancerDeletionProtection.
func (mr *MockIELBV2MockRecorder) DisableLoadBalancerDeletionProtection(ctx, loadBalancerArn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableLoadBalancerDeletionProtection", reflect.TypeOf((*MockIELBV2)(nil).DisableLoadBalancerDeletionProtection), ctx, loadBalancerArn)
}
