// Code generated by MockGen. DO NOT EDIT.
// Source: iam_user.go
//
// Generated by this command:
//
//	mockgen -source=iam_user.go -destination=iam_user_mock.go -package=client -write_package_comment=false
//

package client

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIIamUser is a mock of IIamUser interface.
type MockIIamUser struct {
	ctrl     *gomock.Controller
	recorder *MockIIamUserMockRecorder
	isgomock struct{}
}

// MockIIamUserMockRecorder is the mock recorder for MockIIamUser.
type MockIIamUserMockRecorder struct {
	mock *MockIIamUser
}

// NewMockIIamUser creates a new mock instance.
func NewMockIIamUser(ctrl *gomock.Controller) *MockIIamUser {
	mock := &MockIIamUser{ctrl: ctrl}
	mock.recorder = &MockIIamUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIIamUser) EXPECT() *MockIIamUserMockRecorder {
	return m.recorder
}

// CheckUserExists mocks base method.
func (m *MockIIamUser) CheckUserExists(ctx context.Context, userName *string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserExists", ctx, userName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserExists indicates an expected call of CheckUserExists.
func (mr *MockIIamUserMockRecorder) CheckUserExists(ctx, userName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserExists", reflect.TypeOf((*MockIIamUser)(nil).CheckUserExists), ctx, userName)
}

// DeactivateAndDeleteMFADevices mocks base method.
func (m *MockIIamUser) DeactivateAndDeleteMFADevices(ctx context.Context, userName *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateAndDeleteMFADevices", ctx, userName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateAndDeleteMFADevices indicates an expected call of DeactivateAndDeleteMFADevices.
func (mr *MockIIamUserMockRecorder) DeactivateAndDeleteMFADevices(ctx, userName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateAndDeleteMFADevices", reflect.TypeOf((*MockIIamUser)(nil).DeactivateAndDeleteMFADevices), ctx, userName)
}

// DeleteAccessKeys mocks base method.
func (m *MockIIamUser) DeleteAccessKeys(ctx context.Context, userName *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccessKeys", ctx, userName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccessKeys indicates an expected call of DeleteAccessKeys.
func (mr *MockIIamUserMockRecorder) DeleteAccessKeys(ctx, userName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccessKeys", reflect.TypeOf((*MockIIamUser)(nil).DeleteAccessKeys), ctx, userName)
}

// DeleteLoginProfile mocks base method.
func (m *MockIIamUser) DeleteLoginProfile(ctx context.Context, userName *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLoginProfile", ctx, userName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLoginProfile indicates an expected call of DeleteLoginProfile.
func (mr *MockIIamUserMockRecorder) DeleteLoginProfile(ctx, userName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLoginProfile", reflect.TypeOf((*MockIIamUser)(nil).DeleteLoginProfile), ctx, userName)
}

// DeleteSSHPublicKeys mocks base method.
func (m *MockIIamUser) DeleteSSHPublicKeys(ctx context.Context, userName *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSSHPublicKeys", ctx, userName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSSHPublicKeys indicates an expected call of DeleteSSHPublicKeys.
func (mr *MockIIamUserMockRecorder) DeleteSSHPublicKeys(ctx, userName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSSHPublicKeys", reflect.TypeOf((*MockIIamUser)(nil).DeleteSSHPublicKeys), ctx, userName)
}

// DeleteServiceSpecificCredentials mocks base method.
func (m *MockIIamUser) DeleteServiceSpecificCredentials(ctx context.Context, userName *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteServiceSpecificCredentials", ctx, userName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteServiceSpecificCredentials indicates an expected call of DeleteServiceSpecificCredentials.
func (mr *MockIIamUserMockRecorder) DeleteServiceSpecificCredentials(ctx, userName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServiceSpecificCredentials", reflect.TypeOf((*MockIIamUser)(nil).DeleteServiceSpecificCredentials), ctx, userName)
}

// DeleteSigningCertificates mocks base method.
func (m *MockIIamUser) DeleteSigningCertificates(ctx context.Context, userName *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSigningCertificates", ctx, userName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSigningCertificates indicates an expected call of DeleteSigningCertificates.
func (mr *MockIIamUserMockRecorder) DeleteSigningCertificates(ctx, userName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSigningCertificates", reflect.TypeOf((*MockIIamUser)(nil).DeleteSigningCertificates), ctx, userName)
}

// DeleteUser mocks base method.
func (m *MockIIamUser) DeleteUser(ctx context.Context, userName *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, userName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockIIamUserMockRecorder) DeleteUser(ctx, userName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockIIamUser)(nil).DeleteUser), ctx, userName)
}

// DeleteUserInlinePolicies mocks base method.
func (m *MockIIamUser) DeleteUserInlinePolicies(ctx context.Context, userName *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserInlinePolicies", ctx, userName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserInlinePolicies indicates an expected call of DeleteUserInlinePolicies.
func (mr *MockIIamUserMockRecorder) DeleteUserInlinePolicies(ctx, userName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserInlinePolicies", reflect.TypeOf((*MockIIamUser)(nil).DeleteUserInlinePolicies), ctx, userName)
}

// DetachUserPolicies mocks base method.
func (m *MockIIamUser) DetachUserPolicies(ctx context.Context, userName *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetachUserPolicies", ctx, userName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DetachUserPolicies indicates an expected call of DetachUserPolicies.
func (mr *MockIIamUserMockRecorder) DetachUserPolicies(ctx, userName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetachUserPolicies", reflect.TypeOf((*MockIIamUser)(nil).DetachUserPolicies), ctx, userName)
}

// RemoveUserFromGroups mocks base method.
func (m *MockIIamUser) RemoveUserFromGroups(ctx context.Context, userName *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserFromGroups", ctx, userName)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUserFromGroups indicates an expected call of RemoveUserFromGroups.
func (mr *MockIIamUserMockRecorder) RemoveUserFromGroups(ctx, userName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserFromGroups", reflect.TypeOf((*MockIIamUser)(nil).RemoveUserFromGroups), ctx, userName)
}
