// Code generated by MockGen. DO NOT EDIT.
// Source: lambda.go
//
// Generated by this command:
//
//	mockgen -source=lambda.go -destination=lambda_mock.go -package=client -write_package_comment=false
//

package client

import (
	context "context"
	reflect "reflect"

	lambda "github.com/aws/aws-sdk-go-v2/service/lambda"
	gomock "go.uber.org/mock/gomock"
)

// MockILambda is a mock of ILambda interface.
type MockILambda struct {
	ctrl     *gomock.Controller
	recorder *MockILambdaMockRecorder
	isgomock struct{}
}

// MockILambdaMockRecorder is the mock recorder for MockILambda.
type MockILambdaMockRecorder struct {
	mock *MockILambda
}

// NewMockILambda creates a new mock instance.
func NewMockILambda(ctrl *gomock.Controller) *MockILambda {
	mock := &MockILambda{ctrl: ctrl}
	mock.recorder = &MockILambdaMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILambda) EXPECT() *MockILambdaMockRecorder {
	return m.recorder
}

// CheckLambdaFunctionExists mocks base method.
func (m *MockILambda) CheckLambdaFunctionExists(ctx context.Context, functionName *string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckLambdaFunctionExists", ctx, functionName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckLambdaFunctionExists indicates an expected call of CheckLambdaFunctionExists.
func (mr *MockILambdaMockRecorder) CheckLambdaFunctionExists(ctx, functionName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckLambdaFunctionExists", reflect.TypeOf((*MockILambda)(nil).CheckLambdaFunctionExists), ctx, functionName)
}

// DeleteFunction mocks base method.
func (m *MockILambda) DeleteFunction(ctx context.Context, functionName *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFunction", ctx, functionName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFunction indicates an expected call of DeleteFunction.
func (mr *MockILambdaMockRecorder) DeleteFunction(ctx, functionName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFunction", reflect.TypeOf((*MockILambda)(nil).DeleteFunction), ctx, functionName)
}

// GetFunction mocks base method.
func (m *MockILambda) GetFunction(ctx context.Context, functionName *string) (*lambda.GetFunctionOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFunction", ctx, functionName)
	ret0, _ := ret[0].(*lambda.GetFunctionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFunction indicates an expected call of GetFunction.
func (mr *MockILambdaMockRecorder) GetFunction(ctx, functionName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFunction", reflect.TypeOf((*MockILambda)(nil).GetFunction), ctx, functionName)
}

// UpdateFunctionConfiguration mocks base method.
func (m *MockILambda) UpdateFunctionConfiguration(ctx context.Context, input *lambda.UpdateFunctionConfigurationInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFunctionConfiguration", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFunctionConfiguration indicates an expected call of UpdateFunctionConfiguration.
func (mr *MockILambdaMockRecorder) UpdateFunctionConfiguration(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFunctionConfiguration", reflect.TypeOf((*MockILambda)(nil).UpdateFunctionConfiguration), ctx, input)
}
