// Code generated by MockGen. DO NOT EDIT.
// Source: rds.go
//
// Generated by this command:
//
//	mockgen -source=rds.go -destination=rds_mock.go -package=client -write_package_comment=false
//

package client

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIRDS is a mock of IRDS interface.
type MockIRDS struct {
	ctrl     *gomock.Controller
	recorder *MockIRDSMockRecorder
	isgomock struct{}
}

// MockIRDSMockRecorder is the mock recorder for MockIRDS.
type MockIRDSMockRecorder struct {
	mock *MockIRDS
}

// NewMockIRDS creates a new mock instance.
func NewMockIRDS(ctrl *gomock.Controller) *MockIRDS {
	mock := &MockIRDS{ctrl: ctrl}
	mock.recorder = &MockIRDSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRDS) EXPECT() *MockIRDSMockRecorder {
	return m.recorder
}

// CheckDBClusterDeletionProtection mocks base method.
func (m *MockIRDS) CheckDBClusterDeletionProtection(ctx context.Context, dbClusterId *string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckDBClusterDeletionProtection", ctx, dbClusterId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckDBClusterDeletionProtection indicates an expected call of CheckDBClusterDeletionProtection.
func (mr *MockIRDSMockRecorder) CheckDBClusterDeletionProtection(ctx, dbClusterId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckDBClusterDeletionProtection", reflect.TypeOf((*MockIRDS)(nil).CheckDBClusterDeletionProtection), ctx, dbClusterId)
}

// CheckDBInstanceDeletionProtection mocks base method.
func (m *MockIRDS) CheckDBInstanceDeletionProtection(ctx context.Context, dbInstanceId *string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckDBInstanceDeletionProtection", ctx, dbInstanceId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckDBInstanceDeletionProtection indicates an expected call of CheckDBInstanceDeletionProtection.
func (mr *MockIRDSMockRecorder) CheckDBInstanceDeletionProtection(ctx, dbInstanceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckDBInstanceDeletionProtection", reflect.TypeOf((*MockIRDS)(nil).CheckDBInstanceDeletionProtection), ctx, dbInstanceId)
}

// DisableDBClusterDeletionProtection mocks base method.
func (m *MockIRDS) DisableDBClusterDeletionProtection(ctx context.Context, dbClusterId *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableDBClusterDeletionProtection", ctx, dbClusterId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableDBClusterDeletionProtection indicates an expected call of DisableDBClusterDeletionProtection.
func (mr *MockIRDSMockRecorder) DisableDBClusterDeletionProtection(ctx, dbClusterId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableDBClusterDeletionProtection", reflect.TypeOf((*MockIRDS)(nil).DisableDBClusterDeletionProtection), ctx, dbClusterId)
}

// DisableDBInstanceDeletionProtection mocks base method.
func (m *MockIRDS) DisableDBInstanceDeletionProtection(ctx context.Context, dbInstanceId *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableDBInstanceDeletionProtection", ctx, dbInstanceId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableDBInstanceDeletionProtection indicates an expected call of DisableDBInstanceDeletionProtection.
func (mr *MockIRDSMockRecorder) DisableDBInstanceDeletionProtection(ctx, dbInstanceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableDBInstanceDeletionProtection", reflect.TypeOf((*MockIRDS)(nil).DisableDBInstanceDeletionProtection), ctx, dbInstanceId)
}
